export const SITUACAO_FUNCIONARIO_LABELS = {
  ATIVO: 'Ativo',
  INATIVO: 'Inativo',
  AFASTADO: 'Afastado',
  BLOQUEADO: 'Bloqueado',
  APOSENTADO: 'Aposentado',
} as const

export const SITUACAO_AVERBACAO_LABELS = {
  AGUARDANDO_APROVACAO: 'Aguardando Aprovacao',
  APROVADA: 'Aprovada',
  REJEITADA: 'Rejeitada',
  ENVIADA: 'Enviada',
  DESCONTADA: 'Descontada',
  SUSPENSA: 'Suspensa',
  BLOQUEADA: 'Bloqueada',
  LIQUIDADA: 'Liquidada',
  CANCELADA: 'Cancelada',
} as const

export const TIPO_OPERACAO_LABELS = {
  NOVO: 'Novo',
  REFINANCIAMENTO: 'Refinanciamento',
  COMPRA_DIVIDA: 'Compra de Divida',
} as const

export const TIPO_PRODUTO_LABELS = {
  EMPRESTIMO: 'Emprestimo',
  CARTAO: 'Cartao',
  SEGURO: 'Seguro',
} as const

export const TIPO_PERFIL_LABELS = {
  SISTEMA: 'Sistema',
  CONSIGNANTE: 'Consignante',
  CONSIGNATARIA: 'Consignataria',
  AGENTE: 'Agente',
} as const

export const STATUS_CONCILIACAO_LABELS = {
  ABERTA: 'Aberta',
  EM_ANDAMENTO: 'Em Andamento',
  FECHADA: 'Fechada',
} as const

export const STATUS_IMPORTACAO_LABELS = {
  PENDENTE: 'Pendente',
  PROCESSANDO: 'Processando',
  CONCLUIDO: 'Concluido',
  ERRO: 'Erro',
  CANCELADO: 'Cancelado',
} as const

export const TIPO_IMPORTACAO_LABELS = {
  FUNCIONARIOS: 'Funcionarios',
  CONTRATOS: 'Contratos',
  RETORNO_FOLHA: 'Retorno de Folha',
} as const

export const PERMISSOES = {
  // Funcionarios
  FUNCIONARIOS_VISUALIZAR: 'FUNCIONARIOS_VISUALIZAR',
  FUNCIONARIOS_CRIAR: 'FUNCIONARIOS_CRIAR',
  FUNCIONARIOS_EDITAR: 'FUNCIONARIOS_EDITAR',
  FUNCIONARIOS_EXCLUIR: 'FUNCIONARIOS_EXCLUIR',

  // Averbacoes
  AVERBACOES_VISUALIZAR: 'AVERBACOES_VISUALIZAR',
  AVERBACOES_CRIAR: 'AVERBACOES_CRIAR',
  AVERBACOES_EDITAR: 'AVERBACOES_EDITAR',
  AVERBACOES_APROVAR: 'AVERBACOES_APROVAR',
  AVERBACOES_SUSPENDER: 'AVERBACOES_SUSPENDER',
  AVERBACOES_CANCELAR: 'AVERBACOES_CANCELAR',

  // Margem
  MARGEM_VISUALIZAR: 'MARGEM_VISUALIZAR',
  MARGEM_RESERVAR: 'MARGEM_RESERVAR',

  // Consignatarias
  CONSIGNATARIAS_VISUALIZAR: 'CONSIGNATARIAS_VISUALIZAR',
  CONSIGNATARIAS_GERENCIAR: 'CONSIGNATARIAS_GERENCIAR',

  // Conciliacao
  CONCILIACAO_VISUALIZAR: 'CONCILIACAO_VISUALIZAR',
  CONCILIACAO_CRIAR: 'CONCILIACAO_CRIAR',
  CONCILIACAO_TRATAR: 'CONCILIACAO_TRATAR',
  CONCILIACAO_FECHAR: 'CONCILIACAO_FECHAR',

  // Importacao
  IMPORTACAO_VISUALIZAR: 'IMPORTACAO_VISUALIZAR',
  IMPORTACAO_CRIAR: 'IMPORTACAO_CRIAR',

  // Relatorios
  RELATORIOS_VISUALIZAR: 'RELATORIOS_VISUALIZAR',
  RELATORIOS_EXPORTAR: 'RELATORIOS_EXPORTAR',

  // Auditoria
  AUDITORIA_VISUALIZAR: 'AUDITORIA_VISUALIZAR',

  // Configuracoes
  CONFIGURACOES_VISUALIZAR: 'CONFIGURACOES_VISUALIZAR',
  CONFIGURACOES_EDITAR: 'CONFIGURACOES_EDITAR',

  // Usuarios
  USUARIOS_VISUALIZAR: 'USUARIOS_VISUALIZAR',
  USUARIOS_GERENCIAR: 'USUARIOS_GERENCIAR',
} as const

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
} as const

export const FILE_UPLOAD_LIMITS = {
  MAX_SIZE_BYTES: 10 * 1024 * 1024, // 10MB
  ALLOWED_EXTENSIONS: ['.xlsx', '.xls', '.csv', '.txt'],
} as const
