//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int IDAuditoria { get; set; }
        public Nullable<int> IDModulo { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<int> IDRecurso { get; set; }
        public Nullable<int> IDPerfil { get; set; }
        public string NomeRecurso { get; set; }
        public System.DateTime Data { get; set; }
        public string Tabela { get; set; }
        public Nullable<int> Chave { get; set; }
        public string TipoOperacao { get; set; }
        public string Registro { get; set; }
        public string IP { get; set; }
        public string Browser { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual Recurso Recurso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
