//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AverbacaoTramitacao
    {
        public int IDAverbacaoTramitacao { get; set; }
        public int IDAverbacao { get; set; }
        public int IDAverbacaoSituacao { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
        public string OBS { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Averbacao Averbacao { get; set; }
        public virtual AverbacaoSituacao AverbacaoSituacao { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
