//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AverbacaoParcela
    {
        public AverbacaoParcela()
        {
            this.ConciliacaoCorteFolha = new HashSet<ConciliacaoCorteFolha>();
        }
    
        public int IDAverbacaoParcela { get; set; }
        public int IDAverbacao { get; set; }
        public int IDAverbacaoParcelaSituacao { get; set; }
        public int Numero { get; set; }
        public string Competencia { get; set; }
        public decimal Valor { get; set; }
        public Nullable<decimal> ValorDescontado { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Ativo { get; set; }
    
        public virtual Averbacao Averbacao { get; set; }
        public virtual ICollection<ConciliacaoCorteFolha> ConciliacaoCorteFolha { get; set; }
        public virtual AverbacaoParcelaSituacao AverbacaoParcelaSituacao { get; set; }
    }
}
