//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AverbacaoVinculo
    {
        public int IDAverbacaoVinculo { get; set; }
        public int IDAverbacao { get; set; }
        public int IDAverbacaoPai { get; set; }
    
        public virtual Averbacao Averbacao { get; set; }
        public virtual Averbacao Averbacao1 { get; set; }
    }
}
