//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AverbacaoImportacao
    {
        public int Id { get; set; }
        public string Matricula { get; set; }
        public string CPF { get; set; }
        public string ParcelaCorrente { get; set; }
        public string MesAnoPrimeiraParcela { get; set; }
        public string MesAnoParcelaCorrente { get; set; }
        public string Data { get; set; }
        public string Identificador { get; set; }
        public string Numero { get; set; }
        public Nullable<decimal> ValorParcela { get; set; }
        public string ValorDeducaoMargem { get; set; }
        public Nullable<int> Prazo { get; set; }
        public string CET { get; set; }
        public Nullable<decimal> ValorContratado { get; set; }
        public Nullable<decimal> ValorDevidoTotal { get; set; }
        public string CompetenciaInicial { get; set; }
        public string CompetenciaFinal { get; set; }
        public string Coeficiente { get; set; }
        public string Obs { get; set; }
        public string PrazoAprovacao { get; set; }
        public string Verba { get; set; }
        public Nullable<int> IdImportacao { get; set; }
    }
}
