//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Averbacao
    {
        public Averbacao()
        {
            this.AverbacaoAjusteDetalhe = new HashSet<AverbacaoAjusteDetalhe>();
            this.AverbacaoHistorico = new HashSet<AverbacaoHistorico>();
            this.AverbacaoParcela = new HashSet<AverbacaoParcela>();
            this.AverbacaoTramitacao = new HashSet<AverbacaoTramitacao>();
            this.AverbacaoVinculo = new HashSet<AverbacaoVinculo>();
            this.AverbacaoVinculo1 = new HashSet<AverbacaoVinculo>();
            this.EmpresaSolicitacao = new HashSet<EmpresaSolicitacao>();
        }
    
        public int IDAverbacao { get; set; }
        public int IDProduto { get; set; }
        public int IDConsignataria { get; set; }
        public Nullable<int> IDAgente { get; set; }
        public int IDFuncionario { get; set; }
        public int IDAverbacaoSituacao { get; set; }
        public int IDAverbacaoTipo { get; set; }
        public int IDUsuario { get; set; }
        public System.DateTime Data { get; set; }
        public string Identificador { get; set; }
        public string Numero { get; set; }
        public decimal ValorParcela { get; set; }
        public decimal ValorDeducaoMargem { get; set; }
        public Nullable<int> Prazo { get; set; }
        public Nullable<decimal> CET { get; set; }
        public decimal ValorContratado { get; set; }
        public Nullable<decimal> ValorDevidoTotal { get; set; }
        public Nullable<decimal> ValorRefinanciado { get; set; }
        public string CompetenciaInicial { get; set; }
        public string CompetenciaFinal { get; set; }
        public Nullable<decimal> Coeficiente { get; set; }
        public string Obs { get; set; }
        public Nullable<System.DateTime> PrazoAprovacao { get; set; }
        public Nullable<int> IDAverbacaoPai { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int Ativo { get; set; }
        public decimal ValorTroco { get; set; }
    
        public virtual AverbacaoSituacao AverbacaoSituacao { get; set; }
        public virtual AverbacaoTipo AverbacaoTipo { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual Empresa Empresa2 { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<AverbacaoAjusteDetalhe> AverbacaoAjusteDetalhe { get; set; }
        public virtual ICollection<AverbacaoHistorico> AverbacaoHistorico { get; set; }
        public virtual ICollection<AverbacaoParcela> AverbacaoParcela { get; set; }
        public virtual ICollection<AverbacaoTramitacao> AverbacaoTramitacao { get; set; }
        public virtual ICollection<AverbacaoVinculo> AverbacaoVinculo { get; set; }
        public virtual ICollection<AverbacaoVinculo> AverbacaoVinculo1 { get; set; }
        public virtual ICollection<EmpresaSolicitacao> EmpresaSolicitacao { get; set; }
    }
}
