//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AverbacaoAjuste
    {
        public AverbacaoAjuste()
        {
            this.AverbacaoAjusteArquivo = new HashSet<AverbacaoAjusteArquivo>();
            this.AverbacaoAjusteDetalhe = new HashSet<AverbacaoAjusteDetalhe>();
        }
    
        public int IDAverbacaoAjuste { get; set; }
        public int IDConsignataria { get; set; }
        public int IDProduto { get; set; }
        public int IDContratoAjusteTipo { get; set; }
        public System.DateTime Data { get; set; }
        public string Descricao { get; set; }
        public decimal NovoValor { get; set; }
        public string NomeArquivo { get; set; }
        public string Situacao { get; set; }
        public Nullable<int> Ativo { get; set; }
    
        public virtual AverbacaoAjusteTipo AverbacaoAjusteTipo { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual ICollection<AverbacaoAjusteArquivo> AverbacaoAjusteArquivo { get; set; }
        public virtual ICollection<AverbacaoAjusteDetalhe> AverbacaoAjusteDetalhe { get; set; }
    }
}
