//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConciliacaoCorteFolha
    {
        public ConciliacaoCorteFolha()
        {
            this.ConciliacaoMovimento = new HashSet<ConciliacaoMovimento>();
        }
    
        public int IDConciliacaoCorteFolha { get; set; }
        public string Competencia { get; set; }
        public int IDAverbacaoParcela { get; set; }
        public int IDAverbacaoSituacao { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public int IDCorteHistorico { get; set; }
        public decimal? ValorParcela { get; set; }
        public string Verba { get; set; }
        public string Matricula { get; set; }
        public Nullable<int> IDProdutoGrupo { get; set; }
        public Nullable<int> IDProdutoTipo { get; set; }
        public Nullable<int> IDConsignataria { get; set; }
        public Nullable<int> IDProduto { get; set; }
        public Nullable<int> IDFuncionario { get; set; }
        public Nullable<int> Prazo { get; set; }
        public Nullable<int> Parcela { get; set; }
    
        public virtual AverbacaoParcela AverbacaoParcela { get; set; }
        public virtual AverbacaoSituacao AverbacaoSituacao { get; set; }
        public virtual CorteHistorico CorteHistorico { get; set; }
        public virtual ICollection<ConciliacaoMovimento> ConciliacaoMovimento { get; set; }
    }
}
