//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConciliacaoRetorno
    {
        public ConciliacaoRetorno()
        {
            this.Conciliacao = new HashSet<Conciliacao>();
        }
    
        public int IDConciliacaoRetorno { get; set; }
        public string Competencia { get; set; }
        public string Matricula { get; set; }
        public string Verba { get; set; }
        public decimal ValorDescontado { get; set; }
        public Nullable<int> IDConsignataria { get; set; }
        public Nullable<int> IDProduto { get; set; }
    
        public virtual ICollection<Conciliacao> Conciliacao { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
