//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConciliacaoMovimento
    {
        public ConciliacaoMovimento()
        {
            this.Conciliacao = new HashSet<Conciliacao>();
        }
    
        public int IDConciliacaoMovimento { get; set; }
        public Nullable<int> IDConciliacaoCorteFolha { get; set; }
        public Nullable<int> IDConciliacaoMovimentoTipo { get; set; }
        public string Competencia { get; set; }
        public string Matricula { get; set; }
        public string Verba { get; set; }
        public decimal Valor { get; set; }
        public decimal ValorMovimento { get; set; }
        public decimal ValorDescontado { get; set; }
        public Nullable<int> IDConciliacaoRetorno { get; set; }
        public Nullable<int> IDConsignataria { get; set; }
        public Nullable<int> IDProduto { get; set; }
        public Nullable<int> IDAverbacaoParcela { get; set; }
        public Nullable<int> Prazo { get; set; }
        public Nullable<int> Parcela { get; set; }
    
        public virtual ICollection<Conciliacao> Conciliacao { get; set; }
        public virtual ConciliacaoCorteFolha ConciliacaoCorteFolha { get; set; }
        public virtual ConciliacaoMovimentoTipo ConciliacaoMovimentoTipo { get; set; }
    }
}
