//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaIP
    {
        public int IDEmpresaIP { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
        public string IPInicio { get; set; }
        public string IPFim { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
