//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaVinculo
    {
        public int IDEmpresaVinculo { get; set; }
        public int IDEmpresa { get; set; }
        public int IDEmpresaVinculada { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Ativo { get; set; }
    
        public virtual Empresa Consignataria { get; set; }
        public virtual Empresa Agente { get; set; }
    }
}
