//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaCoeficienteDetalhe
    {
        public int IDEmpresaCoeficienteDetalhe { get; set; }
        public int IDEmpresaCoeficiente { get; set; }
        public int Prazo { get; set; }
        public decimal Coeficiente { get; set; }
        public Nullable<decimal> CET { get; set; }
        public Nullable<int> Dia { get; set; }
        public int Ativo { get; set; }
    
        public virtual EmpresaCoeficiente EmpresaCoeficiente { get; set; }
    }
}
