//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.AssuntoResponsavel = new HashSet<AssuntoResponsavel>();
            this.AuditoriaAcesso = new HashSet<AuditoriaAcesso>();
            this.Averbacao = new HashSet<Averbacao>();
            this.Averbacao1 = new HashSet<Averbacao>();
            this.Averbacao2 = new HashSet<Averbacao>();
            this.AverbacaoAjuste = new HashSet<AverbacaoAjuste>();
            this.AverbacaoTramitacao = new HashSet<AverbacaoTramitacao>();
            this.Conciliacao = new HashSet<Conciliacao>();
            this.ConciliacaoRetorno = new HashSet<ConciliacaoRetorno>();
            this.EmpresaContato = new HashSet<EmpresaContato>();
            this.EmpresaIP = new HashSet<EmpresaIP>();
            this.EmpresaSuspensao = new HashSet<EmpresaSuspensao>();
            this.EmpresaUsuario = new HashSet<EmpresaUsuario>();
            this.EmpresaVinculo = new HashSet<EmpresaVinculo>();
            this.EmpresaVinculo1 = new HashSet<EmpresaVinculo>();
            this.Perfil = new HashSet<Perfil>();
            this.PermissaoUsuario = new HashSet<PermissaoUsuario>();
            this.Produto = new HashSet<Produto>();
            this.Produto1 = new HashSet<Produto>();
            this.ProdutoGrupo = new HashSet<ProdutoGrupo>();
            this.TmpBoasNoticias = new HashSet<TmpBoasNoticias>();
            this.TmpMasNoticias = new HashSet<TmpMasNoticias>();
            this.UsuarioPerfil = new HashSet<UsuarioPerfil>();
            this.UsuarioResponsabilidade = new HashSet<UsuarioResponsabilidade>();
            this.IndiceNegocioAntecipar = new HashSet<IndiceNegocioAntecipar>();
            this.IndiceNegocioRealizado = new HashSet<IndiceNegocioRealizado>();
            this.IndiceNegocioRealizar = new HashSet<IndiceNegocioRealizar>();
            this.EmpresaSolicitacao = new HashSet<EmpresaSolicitacao>();
            this.EmpresaSolicitacao1 = new HashSet<EmpresaSolicitacao>();
        }
    
        public int IDEmpresa { get; set; }
        public int IDEmpresaTipo { get; set; }
        public Nullable<int> IDEmpresaLogo { get; set; }
        public string ArquivoLogo { get; set; }
        public string CNPJ { get; set; }
        public string RazaoSocial { get; set; }
        public string Fantasia { get; set; }
        public string Sigla { get; set; }
        public string Endereco { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CEP { get; set; }
        public string Fone1 { get; set; }
        public string Fone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Site { get; set; }
        public int IDEmpresaSituacao { get; set; }
        public Nullable<int> IDEmpresaSituacaoAnterior { get; set; }
        public Nullable<int> IDUsuarioResponsavel { get; set; }
        public Nullable<int> RepasseDia { get; set; }
        public string RepasseBanco { get; set; }
        public string RepasseAgencia { get; set; }
        public string RepasseConta { get; set; }
        public string RepasseIDFederal { get; set; }
        public string RepasseFavorecido { get; set; }
        public int IDEmpresaTarifada { get; set; }
        public Nullable<decimal> ValorTarifa { get; set; }
        public Nullable<int> IDEmpresaAgenteTipo { get; set; }
        public Nullable<bool> HomologacaoRequerida { get; set; }
        public Nullable<System.DateTime> HomologacaoData { get; set; }
        public Nullable<int> IDUsuarioHomologacao { get; set; }
        public Nullable<bool> ContribuinteFastConsig { get; set; }
        public Nullable<int> IDContribuinteFastConsig { get; set; }
        public Nullable<int> DiaCorte { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int Ativo { get; set; }
    
        public virtual ICollection<AssuntoResponsavel> AssuntoResponsavel { get; set; }
        public virtual ICollection<AuditoriaAcesso> AuditoriaAcesso { get; set; }
        public virtual ICollection<Averbacao> Averbacao { get; set; }
        public virtual ICollection<Averbacao> Averbacao1 { get; set; }
        public virtual ICollection<Averbacao> Averbacao2 { get; set; }
        public virtual ICollection<AverbacaoAjuste> AverbacaoAjuste { get; set; }
        public virtual ICollection<AverbacaoTramitacao> AverbacaoTramitacao { get; set; }
        public virtual ICollection<Conciliacao> Conciliacao { get; set; }
        public virtual ICollection<ConciliacaoRetorno> ConciliacaoRetorno { get; set; }
        public virtual EmpresaLogo EmpresaLogo { get; set; }
        public virtual EmpresaSituacao EmpresaSituacao { get; set; }
        public virtual EmpresaSituacao EmpresaSituacao1 { get; set; }
        public virtual EmpresaTarifada EmpresaTarifada { get; set; }
        public virtual EmpresaTipo EmpresaTipo { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<EmpresaContato> EmpresaContato { get; set; }
        public virtual ICollection<EmpresaIP> EmpresaIP { get; set; }
        public virtual ICollection<EmpresaSuspensao> EmpresaSuspensao { get; set; }
        public virtual ICollection<EmpresaUsuario> EmpresaUsuario { get; set; }
        public virtual ICollection<EmpresaVinculo> EmpresaVinculo { get; set; }
        public virtual ICollection<EmpresaVinculo> EmpresaVinculo1 { get; set; }
        public virtual ICollection<Perfil> Perfil { get; set; }
        public virtual ICollection<PermissaoUsuario> PermissaoUsuario { get; set; }
        public virtual ICollection<Produto> Produto { get; set; }
        public virtual ICollection<Produto> Produto1 { get; set; }
        public virtual ICollection<ProdutoGrupo> ProdutoGrupo { get; set; }
        public virtual ICollection<TmpBoasNoticias> TmpBoasNoticias { get; set; }
        public virtual ICollection<TmpMasNoticias> TmpMasNoticias { get; set; }
        public virtual ICollection<UsuarioPerfil> UsuarioPerfil { get; set; }
        public virtual ICollection<UsuarioResponsabilidade> UsuarioResponsabilidade { get; set; }
        public virtual ICollection<IndiceNegocioAntecipar> IndiceNegocioAntecipar { get; set; }
        public virtual ICollection<IndiceNegocioRealizado> IndiceNegocioRealizado { get; set; }
        public virtual ICollection<IndiceNegocioRealizar> IndiceNegocioRealizar { get; set; }
        public virtual ICollection<EmpresaSolicitacao> EmpresaSolicitacao { get; set; }
        public virtual ICollection<EmpresaSolicitacao> EmpresaSolicitacao1 { get; set; }
    }
}
