//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Empresa = new HashSet<Empresa>();
        }
    
        public string SiglaEstado { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Empresa> Empresa { get; set; }
    }
}
