//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fluxo
    {
        public Fluxo()
        {
            this.FluxoDetalhe = new HashSet<FluxoDetalhe>();
        }
    
        public int IDFluxo { get; set; }
        public Nullable<int> IDFluxoTipo { get; set; }
        public Nullable<int> IDProdutoGrupo { get; set; }
    
        public virtual FluxoTipo FluxoTipo { get; set; }
        public virtual ProdutoGrupo ProdutoGrupo { get; set; }
        public virtual ICollection<FluxoDetalhe> FluxoDetalhe { get; set; }
    }
}
