//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public Funcionario()
        {
            this.Averbacao = new HashSet<Averbacao>();
            this.AverbacaoAjusteDetalhe = new HashSet<AverbacaoAjusteDetalhe>();
            this.Conciliacao = new HashSet<Conciliacao>();
            this.FuncionarioAutorizacao = new HashSet<FuncionarioAutorizacao>();
            this.FuncionarioBloqueio = new HashSet<FuncionarioBloqueio>();
            this.FuncionarioHistorico = new HashSet<FuncionarioHistorico>();
            this.FuncionarioMargem = new HashSet<FuncionarioMargem>();
            this.FuncionarioMargemCargaDados = new HashSet<FuncionarioMargemCargaDados>();
        }
    
        public int IDFuncionario { get; set; }
        public int IDPessoa { get; set; }
        public string Matricula { get; set; }
        public string MatriculaAntiga { get; set; }
        public Nullable<System.DateTime> DataAdmissao { get; set; }
        public Nullable<int> IDConsignante { get; set; }
        public Nullable<int> IDFuncionarioCategoria { get; set; }
        public Nullable<int> IDFuncionarioSituacao { get; set; }
        public Nullable<int> IDFuncionarioRegime { get; set; }
        public string NomeLocalFolha { get; set; }
        public string NomeSetorFolha { get; set; }
        public string NomeCargoFolha { get; set; }
        public string NomeRegimeFolha { get; set; }
        public string NomeSituacaoFolha { get; set; }
        public Nullable<decimal> MargemBruta { get; set; }
        public Nullable<decimal> MargemBase { get; set; }
        public string FonteRecurso { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int Ativo { get; set; }
        public string MESEXONERAR { get; set; }
    
        public virtual ICollection<Averbacao> Averbacao { get; set; }
        public virtual ICollection<AverbacaoAjusteDetalhe> AverbacaoAjusteDetalhe { get; set; }
        public virtual ICollection<Conciliacao> Conciliacao { get; set; }
        public virtual FuncionarioCategoria FuncionarioCategoria { get; set; }
        public virtual FuncionarioRegime FuncionarioRegime { get; set; }
        public virtual FuncionarioSituacao FuncionarioSituacao { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual ICollection<FuncionarioAutorizacao> FuncionarioAutorizacao { get; set; }
        public virtual ICollection<FuncionarioBloqueio> FuncionarioBloqueio { get; set; }
        public virtual ICollection<FuncionarioHistorico> FuncionarioHistorico { get; set; }
        public virtual ICollection<FuncionarioMargem> FuncionarioMargem { get; set; }
        public virtual ICollection<FuncionarioMargemCargaDados> FuncionarioMargemCargaDados { get; set; }
    }
}
