//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionarioAposenta
    {
        public int IDFuncionarioAposenta { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IDFuncionario { get; set; }
        public string Matricula { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Numero { get; set; }
        public string Identificador { get; set; }
        public string CompetenciaInicial { get; set; }
        public string CompetenciaFinal { get; set; }
        public Nullable<int> Prazo { get; set; }
        public Nullable<decimal> ValorParcela { get; set; }
        public string NomeConsignataria { get; set; }
        public string Verba { get; set; }
        public Nullable<decimal> ValorContrato { get; set; }
        public Nullable<bool> Importado { get; set; }
    }
}
