//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionarioHistorico
    {
        public int IDFuncionarioHistorico { get; set; }
        public Nullable<int> IDFuncionario { get; set; }
        public Nullable<int> IDFuncionarioSituacao { get; set; }
        public Nullable<int> IDFuncionarioRegime { get; set; }
        public string NomeSituacaoFolha { get; set; }
        public string NomeRegimeFolha { get; set; }
        public string NomeLocalFolha { get; set; }
        public string NomeCargoFolha { get; set; }
        public string NomeSetorFolha { get; set; }
        public Nullable<decimal> MargemFolhaBruta { get; set; }
        public Nullable<decimal> MargemFolhaDisponivel { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Competencia { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual FuncionarioRegime FuncionarioRegime { get; set; }
        public virtual FuncionarioSituacao FuncionarioSituacao { get; set; }
    }
}
