//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionarioMargem
    {
        public int IDFuncionarioMargem { get; set; }
        public int IDFuncionario { get; set; }
        public int IDProdutoGrupo { get; set; }
        public decimal MargemFolha { get; set; }
        public decimal MargemFolhaDisponivel { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual ProdutoGrupo ProdutoGrupo { get; set; }
    }
}
