//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndiceNegocioRealizar
    {
        public int IDIndiceNegRealizar { get; set; }
        public string Competencia { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> MargemDisponivel { get; set; }
        public Nullable<decimal> VolumeNegocio { get; set; }
        public Nullable<decimal> VolumeAdicionado { get; set; }
        public Nullable<decimal> MargemUtilizada { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
