//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensagemSistema
    {
        public int IDMensagemSistema { get; set; }
        public string Titulo { get; set; }
        public string Texto { get; set; }
        public string TextoHTML { get; set; }
        public Nullable<int> IDModulo { get; set; }
        public string Perfis { get; set; }
        public bool DispararEmail { get; set; }
        public bool DispararSMS { get; set; }
        public bool ForcarLeitura { get; set; }
    }
}
