//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.Auditoria = new HashSet<Auditoria>();
            this.AuditoriaAcesso = new HashSet<AuditoriaAcesso>();
            this.Aviso = new HashSet<Aviso>();
        }
    
        public int IDModulo { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Auditoria> Auditoria { get; set; }
        public virtual ICollection<AuditoriaAcesso> AuditoriaAcesso { get; set; }
        public virtual ICollection<Aviso> Aviso { get; set; }
    }
}
