//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public Perfil()
        {
            this.AuditoriaAcesso = new HashSet<AuditoriaAcesso>();
            this.PermissaoUsuario = new HashSet<PermissaoUsuario>();
            this.UsuarioPerfil = new HashSet<UsuarioPerfil>();
        }
    
        public int IDPerfil { get; set; }
        public string Nome { get; set; }
        public string Sigla { get; set; }
        public int IDModulo { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
    
        public virtual ICollection<AuditoriaAcesso> AuditoriaAcesso { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<PermissaoUsuario> PermissaoUsuario { get; set; }
        public virtual ICollection<UsuarioPerfil> UsuarioPerfil { get; set; }
    }
}
