//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissao
    {
        public Permissao()
        {
            this.PermissaoRecurso = new HashSet<PermissaoRecurso>();
            this.PermissaoSistema = new HashSet<PermissaoSistema>();
            this.PermissaoUsuario = new HashSet<PermissaoUsuario>();
        }
    
        public int IDPermissao { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<PermissaoRecurso> PermissaoRecurso { get; set; }
        public virtual ICollection<PermissaoSistema> PermissaoSistema { get; set; }
        public virtual ICollection<PermissaoUsuario> PermissaoUsuario { get; set; }
    }
}
