//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Funcionario = new HashSet<Funcionario>();
            this.FuncionarioCargaDados = new HashSet<FuncionarioCargaDados>();
        }
    
        public int IDPessoa { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public string Endereco { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CEP { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string NomeMae { get; set; }
        public string NomePai { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Ativo { get; set; }
        public string Fone { get; set; }
    
        public virtual ICollection<Funcionario> Funcionario { get; set; }
        public virtual ICollection<FuncionarioCargaDados> FuncionarioCargaDados { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
