//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpBoasNoticiasDetalhe
    {
        public int Id { get; set; }
        public Nullable<int> IdBoaNoticia { get; set; }
        public string Cpf { get; set; }
        public string Matricula { get; set; }
        public string Nome { get; set; }
        public Nullable<decimal> MargemAnterior { get; set; }
        public Nullable<decimal> MargemAtual { get; set; }
        public Nullable<decimal> Possibilidade { get; set; }
        public Nullable<decimal> SaldoRestante { get; set; }
        public string Telefone { get; set; }
    }
}
