//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpColocacaoConvenio
    {
        public int id { get; set; }
        public Nullable<int> IDServicoGrupo { get; set; }
        public Nullable<int> Qtde { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
        public string Competencia { get; set; }
        public string Tipo { get; set; }
    }
}
