//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpInadimplenciaTempo
    {
        public TmpInadimplenciaTempo()
        {
            this.TmpInadimplenciaTempoDetalhe = new HashSet<TmpInadimplenciaTempoDetalhe>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Valor { get; set; }
    
        public virtual ICollection<TmpInadimplenciaTempoDetalhe> TmpInadimplenciaTempoDetalhe { get; set; }
    }
}
