//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpMasNoticiasInadiplentes
    {
        public TmpMasNoticiasInadiplentes()
        {
            this.TmpMasNoticiasInadiplentesDetalhe = new HashSet<TmpMasNoticiasInadiplentesDetalhe>();
        }
    
        public int Id { get; set; }
        public string DescricaoGrupo { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> NaoConciliado { get; set; }
        public Nullable<int> QuantidadeContrato { get; set; }
        public Nullable<int> Parcelas { get; set; }
        public string Competencia { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
    
        public virtual ICollection<TmpMasNoticiasInadiplentesDetalhe> TmpMasNoticiasInadiplentesDetalhe { get; set; }
    }
}
