//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpNaoRecuperavel
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Matricula { get; set; }
        public string CPF { get; set; }
        public Nullable<decimal> Parcela { get; set; }
        public string Pagas_Prazo { get; set; }
        public Nullable<decimal> SaldoRestante { get; set; }
        public string Competencia { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
    }
}
