//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.FastConsig.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioResponsabilidade
    {
        public int IDUsuarioResponsabilidade { get; set; }
        public int IDUsuario { get; set; }
        public int IDEmpresa { get; set; }
        public int IDEmpresaSolicitacaoTipo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual EmpresaSolicitacaoTipo EmpresaSolicitacaoTipo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
