//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FastConsigCenterModelo", "FK_Vinculo_Consignante", "Consignante", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CP.FastConsig.Services.Consignante), "Vinculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CP.FastConsig.Services.Vinculo), true)]
[assembly: EdmRelationshipAttribute("FastConsigCenterModelo", "FK_Vinculo_Consignataria", "Consignataria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CP.FastConsig.Services.Consignataria), "Vinculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CP.FastConsig.Services.Vinculo), true)]
[assembly: EdmRelationshipAttribute("FastConsigCenterModelo", "FK_UsuarioHistorico_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CP.FastConsig.Services.Usuario), "UsuarioHistorico", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CP.FastConsig.Services.UsuarioHistorico), true)]
[assembly: EdmRelationshipAttribute("FastConsigCenterModelo", "FK_UsuarioVinculo_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CP.FastConsig.Services.Usuario), "UsuarioVinculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CP.FastConsig.Services.UsuarioVinculo), true)]
[assembly: EdmRelationshipAttribute("FastConsigCenterModelo", "FK_UsuarioVinculo_Vinculo", "Vinculo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CP.FastConsig.Services.Vinculo), "UsuarioVinculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CP.FastConsig.Services.UsuarioVinculo), true)]
[assembly: EdmRelationshipAttribute("FastConsigCenterModelo", "FK_Usuario_Consignataria", "Consignataria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CP.FastConsig.Services.Consignataria), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CP.FastConsig.Services.Usuario), true)]

#endregion

namespace CP.FastConsig.Services
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FastConsigCenterEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FastConsigCenterEntities object using the connection string found in the 'FastConsigCenterEntities' section of the application configuration file.
        /// </summary>
        public FastConsigCenterEntities() : base("name=FastConsigCenterEntities", "FastConsigCenterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FastConsigCenterEntities object.
        /// </summary>
        public FastConsigCenterEntities(string connectionString) : base(connectionString, "FastConsigCenterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FastConsigCenterEntities object.
        /// </summary>
        public FastConsigCenterEntities(EntityConnection connection) : base(connection, "FastConsigCenterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Consignante> Consignantes
        {
            get
            {
                if ((_Consignantes == null))
                {
                    _Consignantes = base.CreateObjectSet<Consignante>("Consignantes");
                }
                return _Consignantes;
            }
        }
        private ObjectSet<Consignante> _Consignantes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Consignataria> Consignatarias
        {
            get
            {
                if ((_Consignatarias == null))
                {
                    _Consignatarias = base.CreateObjectSet<Consignataria>("Consignatarias");
                }
                return _Consignatarias;
            }
        }
        private ObjectSet<Consignataria> _Consignatarias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UsuarioHistorico> UsuarioHistoricos
        {
            get
            {
                if ((_UsuarioHistoricos == null))
                {
                    _UsuarioHistoricos = base.CreateObjectSet<UsuarioHistorico>("UsuarioHistoricos");
                }
                return _UsuarioHistoricos;
            }
        }
        private ObjectSet<UsuarioHistorico> _UsuarioHistoricos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UsuarioVinculo> UsuarioVinculos
        {
            get
            {
                if ((_UsuarioVinculos == null))
                {
                    _UsuarioVinculos = base.CreateObjectSet<UsuarioVinculo>("UsuarioVinculos");
                }
                return _UsuarioVinculos;
            }
        }
        private ObjectSet<UsuarioVinculo> _UsuarioVinculos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vinculo> Vinculos
        {
            get
            {
                if ((_Vinculos == null))
                {
                    _Vinculos = base.CreateObjectSet<Vinculo>("Vinculos");
                }
                return _Vinculos;
            }
        }
        private ObjectSet<Vinculo> _Vinculos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Consignantes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConsignantes(Consignante consignante)
        {
            base.AddObject("Consignantes", consignante);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Consignatarias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConsignatarias(Consignataria consignataria)
        {
            base.AddObject("Consignatarias", consignataria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UsuarioHistoricos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarioHistoricos(UsuarioHistorico usuarioHistorico)
        {
            base.AddObject("UsuarioHistoricos", usuarioHistorico);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UsuarioVinculos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarioVinculos(UsuarioVinculo usuarioVinculo)
        {
            base.AddObject("UsuarioVinculos", usuarioVinculo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vinculos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVinculos(Vinculo vinculo)
        {
            base.AddObject("Vinculos", vinculo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FastConsigCenterModelo", Name="Consignante")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Consignante : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Consignante object.
        /// </summary>
        /// <param name="iDConsignante">Initial value of the IDConsignante property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        public static Consignante CreateConsignante(global::System.Int32 iDConsignante, global::System.Boolean ativo)
        {
            Consignante consignante = new Consignante();
            consignante.IDConsignante = iDConsignante;
            consignante.Ativo = ativo;
            return consignante;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDConsignante
        {
            get
            {
                return _IDConsignante;
            }
            set
            {
                if (_IDConsignante != value)
                {
                    OnIDConsignanteChanging(value);
                    ReportPropertyChanging("IDConsignante");
                    _IDConsignante = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDConsignante");
                    OnIDConsignanteChanged();
                }
            }
        }
        private global::System.Int32 _IDConsignante;
        partial void OnIDConsignanteChanging(global::System.Int32 value);
        partial void OnIDConsignanteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Logo
        {
            get
            {
                return _Logo;
            }
            set
            {
                OnLogoChanging(value);
                ReportPropertyChanging("Logo");
                _Logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Logo");
                OnLogoChanged();
            }
        }
        private global::System.String _Logo;
        partial void OnLogoChanging(global::System.String value);
        partial void OnLogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BancoDados
        {
            get
            {
                return _BancoDados;
            }
            set
            {
                OnBancoDadosChanging(value);
                ReportPropertyChanging("BancoDados");
                _BancoDados = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BancoDados");
                OnBancoDadosChanged();
            }
        }
        private global::System.String _BancoDados;
        partial void OnBancoDadosChanging(global::System.String value);
        partial void OnBancoDadosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_Vinculo_Consignante", "Vinculo")]
        public EntityCollection<Vinculo> Vinculos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vinculo>("FastConsigCenterModelo.FK_Vinculo_Consignante", "Vinculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vinculo>("FastConsigCenterModelo.FK_Vinculo_Consignante", "Vinculo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FastConsigCenterModelo", Name="Consignataria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Consignataria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Consignataria object.
        /// </summary>
        /// <param name="iDConsignataria">Initial value of the IDConsignataria property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        public static Consignataria CreateConsignataria(global::System.Int32 iDConsignataria, global::System.Boolean ativo)
        {
            Consignataria consignataria = new Consignataria();
            consignataria.IDConsignataria = iDConsignataria;
            consignataria.Ativo = ativo;
            return consignataria;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDConsignataria
        {
            get
            {
                return _IDConsignataria;
            }
            set
            {
                if (_IDConsignataria != value)
                {
                    OnIDConsignatariaChanging(value);
                    ReportPropertyChanging("IDConsignataria");
                    _IDConsignataria = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDConsignataria");
                    OnIDConsignatariaChanged();
                }
            }
        }
        private global::System.Int32 _IDConsignataria;
        partial void OnIDConsignatariaChanging(global::System.Int32 value);
        partial void OnIDConsignatariaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Logo
        {
            get
            {
                return _Logo;
            }
            set
            {
                OnLogoChanging(value);
                ReportPropertyChanging("Logo");
                _Logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Logo");
                OnLogoChanged();
            }
        }
        private global::System.String _Logo;
        partial void OnLogoChanging(global::System.String value);
        partial void OnLogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_Vinculo_Consignataria", "Vinculo")]
        public EntityCollection<Vinculo> Vinculos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vinculo>("FastConsigCenterModelo.FK_Vinculo_Consignataria", "Vinculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vinculo>("FastConsigCenterModelo.FK_Vinculo_Consignataria", "Vinculo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_Usuario_Consignataria", "Usuario")]
        public EntityCollection<Usuario> Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("FastConsigCenterModelo.FK_Usuario_Consignataria", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("FastConsigCenterModelo.FK_Usuario_Consignataria", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FastConsigCenterModelo", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        /// <param name="iDConsignataria">Initial value of the IDConsignataria property.</param>
        public static Usuario CreateUsuario(global::System.Int32 iDUsuario, global::System.Int32 ativo, global::System.Int32 iDConsignataria)
        {
            Usuario usuario = new Usuario();
            usuario.IDUsuario = iDUsuario;
            usuario.Ativo = ativo;
            usuario.IDConsignataria = iDConsignataria;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                if (_IDUsuario != value)
                {
                    OnIDUsuarioChanging(value);
                    ReportPropertyChanging("IDUsuario");
                    _IDUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUsuario");
                    OnIDUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Int32 _Ativo;
        partial void OnAtivoChanging(global::System.Int32 value);
        partial void OnAtivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int32> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedByType
        {
            get
            {
                return _CreatedByType;
            }
            set
            {
                OnCreatedByTypeChanging(value);
                ReportPropertyChanging("CreatedByType");
                _CreatedByType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedByType");
                OnCreatedByTypeChanged();
            }
        }
        private global::System.String _CreatedByType;
        partial void OnCreatedByTypeChanging(global::System.String value);
        partial void OnCreatedByTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedByName
        {
            get
            {
                return _CreatedByName;
            }
            set
            {
                OnCreatedByNameChanging(value);
                ReportPropertyChanging("CreatedByName");
                _CreatedByName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedByName");
                OnCreatedByNameChanged();
            }
        }
        private global::System.String _CreatedByName;
        partial void OnCreatedByNameChanging(global::System.String value);
        partial void OnCreatedByNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDConsignataria
        {
            get
            {
                return _IDConsignataria;
            }
            set
            {
                OnIDConsignatariaChanging(value);
                ReportPropertyChanging("IDConsignataria");
                _IDConsignataria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDConsignataria");
                OnIDConsignatariaChanged();
            }
        }
        private global::System.Int32 _IDConsignataria;
        partial void OnIDConsignatariaChanging(global::System.Int32 value);
        partial void OnIDConsignatariaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_UsuarioHistorico_Usuario", "UsuarioHistorico")]
        public EntityCollection<UsuarioHistorico> UsuarioHistoricos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UsuarioHistorico>("FastConsigCenterModelo.FK_UsuarioHistorico_Usuario", "UsuarioHistorico");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UsuarioHistorico>("FastConsigCenterModelo.FK_UsuarioHistorico_Usuario", "UsuarioHistorico", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_UsuarioVinculo_Usuario", "UsuarioVinculo")]
        public EntityCollection<UsuarioVinculo> UsuarioVinculos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UsuarioVinculo>("FastConsigCenterModelo.FK_UsuarioVinculo_Usuario", "UsuarioVinculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UsuarioVinculo>("FastConsigCenterModelo.FK_UsuarioVinculo_Usuario", "UsuarioVinculo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_Usuario_Consignataria", "Consignataria")]
        public Consignataria Consignataria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consignataria>("FastConsigCenterModelo.FK_Usuario_Consignataria", "Consignataria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consignataria>("FastConsigCenterModelo.FK_Usuario_Consignataria", "Consignataria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Consignataria> ConsignatariaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consignataria>("FastConsigCenterModelo.FK_Usuario_Consignataria", "Consignataria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Consignataria>("FastConsigCenterModelo.FK_Usuario_Consignataria", "Consignataria", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FastConsigCenterModelo", Name="UsuarioHistorico")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsuarioHistorico : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UsuarioHistorico object.
        /// </summary>
        /// <param name="iDUsuarioHistorico">Initial value of the IDUsuarioHistorico property.</param>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        public static UsuarioHistorico CreateUsuarioHistorico(global::System.Int32 iDUsuarioHistorico, global::System.Int32 iDUsuario, global::System.Boolean ativo)
        {
            UsuarioHistorico usuarioHistorico = new UsuarioHistorico();
            usuarioHistorico.IDUsuarioHistorico = iDUsuarioHistorico;
            usuarioHistorico.IDUsuario = iDUsuario;
            usuarioHistorico.Ativo = ativo;
            return usuarioHistorico;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuarioHistorico
        {
            get
            {
                return _IDUsuarioHistorico;
            }
            set
            {
                if (_IDUsuarioHistorico != value)
                {
                    OnIDUsuarioHistoricoChanging(value);
                    ReportPropertyChanging("IDUsuarioHistorico");
                    _IDUsuarioHistorico = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUsuarioHistorico");
                    OnIDUsuarioHistoricoChanged();
                }
            }
        }
        private global::System.Int32 _IDUsuarioHistorico;
        partial void OnIDUsuarioHistoricoChanging(global::System.Int32 value);
        partial void OnIDUsuarioHistoricoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                OnIDUsuarioChanging(value);
                ReportPropertyChanging("IDUsuario");
                _IDUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUsuario");
                OnIDUsuarioChanged();
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UsuarioSerializado
        {
            get
            {
                return _UsuarioSerializado;
            }
            set
            {
                OnUsuarioSerializadoChanging(value);
                ReportPropertyChanging("UsuarioSerializado");
                _UsuarioSerializado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UsuarioSerializado");
                OnUsuarioSerializadoChanged();
            }
        }
        private global::System.String _UsuarioSerializado;
        partial void OnUsuarioSerializadoChanging(global::System.String value);
        partial void OnUsuarioSerializadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedByName
        {
            get
            {
                return _ModifiedByName;
            }
            set
            {
                OnModifiedByNameChanging(value);
                ReportPropertyChanging("ModifiedByName");
                _ModifiedByName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModifiedByName");
                OnModifiedByNameChanged();
            }
        }
        private global::System.String _ModifiedByName;
        partial void OnModifiedByNameChanging(global::System.String value);
        partial void OnModifiedByNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedByType
        {
            get
            {
                return _ModifiedByType;
            }
            set
            {
                OnModifiedByTypeChanging(value);
                ReportPropertyChanging("ModifiedByType");
                _ModifiedByType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModifiedByType");
                OnModifiedByTypeChanged();
            }
        }
        private global::System.String _ModifiedByType;
        partial void OnModifiedByTypeChanging(global::System.String value);
        partial void OnModifiedByTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Acao
        {
            get
            {
                return _Acao;
            }
            set
            {
                OnAcaoChanging(value);
                ReportPropertyChanging("Acao");
                _Acao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Acao");
                OnAcaoChanged();
            }
        }
        private global::System.String _Acao;
        partial void OnAcaoChanging(global::System.String value);
        partial void OnAcaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_UsuarioHistorico_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("FastConsigCenterModelo.FK_UsuarioHistorico_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("FastConsigCenterModelo.FK_UsuarioHistorico_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("FastConsigCenterModelo.FK_UsuarioHistorico_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("FastConsigCenterModelo.FK_UsuarioHistorico_Usuario", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FastConsigCenterModelo", Name="UsuarioVinculo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsuarioVinculo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UsuarioVinculo object.
        /// </summary>
        /// <param name="iDUsuarioVinculo">Initial value of the IDUsuarioVinculo property.</param>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        /// <param name="iDVinculo">Initial value of the IDVinculo property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        public static UsuarioVinculo CreateUsuarioVinculo(global::System.Int32 iDUsuarioVinculo, global::System.Int32 iDUsuario, global::System.Int32 iDVinculo, global::System.Boolean ativo)
        {
            UsuarioVinculo usuarioVinculo = new UsuarioVinculo();
            usuarioVinculo.IDUsuarioVinculo = iDUsuarioVinculo;
            usuarioVinculo.IDUsuario = iDUsuario;
            usuarioVinculo.IDVinculo = iDVinculo;
            usuarioVinculo.Ativo = ativo;
            return usuarioVinculo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuarioVinculo
        {
            get
            {
                return _IDUsuarioVinculo;
            }
            set
            {
                if (_IDUsuarioVinculo != value)
                {
                    OnIDUsuarioVinculoChanging(value);
                    ReportPropertyChanging("IDUsuarioVinculo");
                    _IDUsuarioVinculo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDUsuarioVinculo");
                    OnIDUsuarioVinculoChanged();
                }
            }
        }
        private global::System.Int32 _IDUsuarioVinculo;
        partial void OnIDUsuarioVinculoChanging(global::System.Int32 value);
        partial void OnIDUsuarioVinculoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                OnIDUsuarioChanging(value);
                ReportPropertyChanging("IDUsuario");
                _IDUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUsuario");
                OnIDUsuarioChanged();
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDVinculo
        {
            get
            {
                return _IDVinculo;
            }
            set
            {
                OnIDVinculoChanging(value);
                ReportPropertyChanging("IDVinculo");
                _IDVinculo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDVinculo");
                OnIDVinculoChanged();
            }
        }
        private global::System.Int32 _IDVinculo;
        partial void OnIDVinculoChanging(global::System.Int32 value);
        partial void OnIDVinculoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_UsuarioVinculo_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("FastConsigCenterModelo.FK_UsuarioVinculo_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("FastConsigCenterModelo.FK_UsuarioVinculo_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("FastConsigCenterModelo.FK_UsuarioVinculo_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("FastConsigCenterModelo.FK_UsuarioVinculo_Usuario", "Usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_UsuarioVinculo_Vinculo", "Vinculo")]
        public Vinculo Vinculo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vinculo>("FastConsigCenterModelo.FK_UsuarioVinculo_Vinculo", "Vinculo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vinculo>("FastConsigCenterModelo.FK_UsuarioVinculo_Vinculo", "Vinculo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vinculo> VinculoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vinculo>("FastConsigCenterModelo.FK_UsuarioVinculo_Vinculo", "Vinculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vinculo>("FastConsigCenterModelo.FK_UsuarioVinculo_Vinculo", "Vinculo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FastConsigCenterModelo", Name="Vinculo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vinculo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vinculo object.
        /// </summary>
        /// <param name="iDVinculo">Initial value of the IDVinculo property.</param>
        /// <param name="iDConsignataria">Initial value of the IDConsignataria property.</param>
        /// <param name="iDConsignante">Initial value of the IDConsignante property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        public static Vinculo CreateVinculo(global::System.Int32 iDVinculo, global::System.Int32 iDConsignataria, global::System.Int32 iDConsignante, global::System.Boolean ativo)
        {
            Vinculo vinculo = new Vinculo();
            vinculo.IDVinculo = iDVinculo;
            vinculo.IDConsignataria = iDConsignataria;
            vinculo.IDConsignante = iDConsignante;
            vinculo.Ativo = ativo;
            return vinculo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDVinculo
        {
            get
            {
                return _IDVinculo;
            }
            set
            {
                if (_IDVinculo != value)
                {
                    OnIDVinculoChanging(value);
                    ReportPropertyChanging("IDVinculo");
                    _IDVinculo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDVinculo");
                    OnIDVinculoChanged();
                }
            }
        }
        private global::System.Int32 _IDVinculo;
        partial void OnIDVinculoChanging(global::System.Int32 value);
        partial void OnIDVinculoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDConsignataria
        {
            get
            {
                return _IDConsignataria;
            }
            set
            {
                OnIDConsignatariaChanging(value);
                ReportPropertyChanging("IDConsignataria");
                _IDConsignataria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDConsignataria");
                OnIDConsignatariaChanged();
            }
        }
        private global::System.Int32 _IDConsignataria;
        partial void OnIDConsignatariaChanging(global::System.Int32 value);
        partial void OnIDConsignatariaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDConsignante
        {
            get
            {
                return _IDConsignante;
            }
            set
            {
                OnIDConsignanteChanging(value);
                ReportPropertyChanging("IDConsignante");
                _IDConsignante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDConsignante");
                OnIDConsignanteChanged();
            }
        }
        private global::System.Int32 _IDConsignante;
        partial void OnIDConsignanteChanging(global::System.Int32 value);
        partial void OnIDConsignanteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_Vinculo_Consignante", "Consignante")]
        public Consignante Consignante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consignante>("FastConsigCenterModelo.FK_Vinculo_Consignante", "Consignante").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consignante>("FastConsigCenterModelo.FK_Vinculo_Consignante", "Consignante").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Consignante> ConsignanteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consignante>("FastConsigCenterModelo.FK_Vinculo_Consignante", "Consignante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Consignante>("FastConsigCenterModelo.FK_Vinculo_Consignante", "Consignante", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_Vinculo_Consignataria", "Consignataria")]
        public Consignataria Consignataria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consignataria>("FastConsigCenterModelo.FK_Vinculo_Consignataria", "Consignataria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consignataria>("FastConsigCenterModelo.FK_Vinculo_Consignataria", "Consignataria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Consignataria> ConsignatariaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consignataria>("FastConsigCenterModelo.FK_Vinculo_Consignataria", "Consignataria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Consignataria>("FastConsigCenterModelo.FK_Vinculo_Consignataria", "Consignataria", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FastConsigCenterModelo", "FK_UsuarioVinculo_Vinculo", "UsuarioVinculo")]
        public EntityCollection<UsuarioVinculo> UsuarioVinculos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UsuarioVinculo>("FastConsigCenterModelo.FK_UsuarioVinculo_Vinculo", "UsuarioVinculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UsuarioVinculo>("FastConsigCenterModelo.FK_UsuarioVinculo_Vinculo", "UsuarioVinculo", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
